###########
# BUILDER #
###########

FROM python:3.11.0-alpine as builder

LABEL authors="0gl04q"

WORKDIR /var/www/VibeTorg

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apk update
RUN apk add postgresql-dev gcc python3-dev musl-dev
RUN pip install --upgrade pip

COPY ./requirements.txt ./
RUN pip wheel --no-cache-dir --no-deps --wheel-dir /var/www/VibeTorg/wheels -r requirements.txt


#########
# FINAL #
#########

FROM python:3.11.0-alpine

RUN mkdir -p /home/lending

RUN addgroup -S lending && adduser -S lending -G lending

ENV HOME=/home/lending
ENV APP_HOME=/home/lending/web
RUN mkdir $APP_HOME
RUN mkdir $APP_HOME/static
RUN mkdir $APP_HOME/media
WORKDIR $APP_HOME

RUN apk update && apk add libpq
COPY --from=builder /var/www/VibeTorg/wheels /wheels
COPY --from=builder /var/www/VibeTorg/requirements.txt .
RUN pip install --no-cache /wheels/*

COPY ./entrypoint.prod.sh $APP_HOME

COPY . $APP_HOME

RUN chown -R lending:lending $APP_HOME

USER lending

RUN chmod +x /home/lending/web/entrypoint.prod.sh
ENTRYPOINT ["/home/lending/web/entrypoint.prod.sh"]